#!/bin/bash


## Load the required modules
module load mpt
module load gcc

## compile


## compile with MPI:
mpicxx trapezodial_rule.cpp  -o ex3_yasminexe

## remove object files if there is any!:
# rm *.mod
# rm *.o

